name: 'Article :: Teardown :: Dev'

on: workflow_dispatch

jobs:
  teardown-dev:
    uses: ./.github/workflows/teardown-service.yml
    with:
      stage: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}