# Deploy article app on aws for DEV stage

name: 'Article :: Deploy :: Dev'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-service.yml
    with:
      stage: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
